import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
x.size
print(x.shape)
a = np.zeros((3, 4))
print(a)
b = np.arange(10, 19, 2)
print(b)
c = np.linspace(6, 6.3, 6)
print(c)
d = np.full((3, 4), 5)
print(d)
e = np.random.random((3, 4))
print(e)
f = np.arange(24)
print(f)
print(a.size)
print(a.dtype)