stringValue = "Wipro Technologies";
x = len(stringValue);
print "The length of given string is %d" % x ;
print "The value of the variable is %s" % stringValue;
print "The first location of stringValue variable is %c" % stringValue[0];
print "The first 5 char of stringValue variable is %s" % stringValue[0:5];
print "The 6th to 10th of stringValue variable is %s" % stringValue[6:10];
print "The 6th to end of stringValue variable is %s" % stringValue[6:];
print "Wipro " * 3;
y = stringValue[0:5];
print "The value extracted in variable y is %s" % y;
