hashValue= {};
hashValue["India"]=10000000;
hashValue["China"]=15000000;
hashValue["Japan"]=1000000;
hashValue["Usa"]=5000000;
hashValue["Brazil"]=200000;
print "The Complete Hash Values present is ", hashValue;
print "The population of India is ", hashValue["India"];
print "The key values of hashValues are ", hashValue.keys();
print "The values present in the hash variables are ", hashValue.values();
